name: Deploy Hugo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install Hugo
        run: |
          curl -fSLO https://github.com/gohugoio/hugo/releases/download/v0.134.1/hugo_0.134.1_linux-amd64.deb
          sudo apt install ./hugo_0.134.1_linux-amd64.deb

      - name: Build Hugo site
        run: |
          ls -la
          hugo --minify

      - name: Sync files to web server
        env:
          RSYNC_RSH: 'ssh -o StrictHostKeyChecking=no'
        run: |
          rsync -avz --delete public/ github-actions@dpeckett.dev:~/immutos/
